//
// Created by RenJie on 2018/12/15 0015 10:29.
//

#ifndef ELECTRICALCIGARETTE_ATOMIZER_H
#define ELECTRICALCIGARETTE_ATOMIZER_H

#include "main.h"

//atomizer drive
#define ATOMIZER_DRIVE_PORT GPIOC
#define ATOMIZER_DRIVE_PIN  GPIO_PIN_5

//check the voltage on resistance
#define ATOMIZER_ADC_NODE_1_PORT GPIOD
#define ATOMIZER_ADC_NODE_1_PIN  GPIO_PIN_3
#define ATOMIZER_ADC_NODE_1_CHANNEL ADC1_CHANNEL_4
#define ATOMIZER_ADC_NODE_1_EXTI_PORT EXTI_PORT_GPIOD
#define ATOMIZER_ADC_NODE_1_TRIGGER_CHANNEL ADC1_SCHMITTTRIG_CHANNEL4

//check the voltage on atomizer
#define ATOMIZER_ADC_NODE_2_PORT GPIOD
#define ATOMIZER_ADC_NODE_2_PIN  GPIO_PIN_2
#define ATOMIZER_ADC_NODE_2_CHANNEL  ADC1_CHANNEL_3
#define ATOMIZER_ADC_NODE_2_EXTI_PORT EXTI_PORT_GPIOD
#define ATOMIZER_ADC_NODE_2_TRIGGER_CHANNEL ADC1_SCHMITTTRIG_CHANNEL3



void Atomizer_Init();
bool Is_Atomizer_In();
void Atomizer_In_Out();
void Atomizer_Smoking();

extern bool smokeStatus;

#endif //ELECTRICALCIGARETTE_ATOMIZER_H
